name: 'todos'
services:
  app:
    build: ./app
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./app:/usr/src/app
  
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=todos
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
  
  db_viewer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db: {}